[default]

otlp_enable = false
log_file = "@format {env[BASE_DIR]}/logs/fms.log"
log_level = 10
log_format = "%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s"
PID_FETCHER_URL = "http://localhost:1928/"
PKL_TOKEN_FILE = "@format {env[BASE_DIR]}/conf/token.pkl"
